name: Hello World Cron
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 

      - name: Run script
        run: node scripts/cron.ts
